######################
#                                              #
#       UpgradablesPets Plugin      #
#   developed by SpaicyGaming  #
#                                              #
#######################

MainSettings:
  currency: "$"
  spawnPetAtJoin: true
  babyPets: true
  # %owner% => Pet owner
  # %name% => Pet name (default names are in the next section)
  # %lvl% => Pet level
  petNameFormat: "&b%owner%'s &6%name% &c(lvl.%lvl%)"
  maxPetNameLenght: 25
  showPetHereMsg: true
  showPetAwayMsg: true
  # Pet respawn delay in minutes
  petRespawnDelay: 1

PetsCost:
  Cow:
    active: true
    name: "&bCow"
    price: 500
  Pig:
    active: true
    name: "&dPig"
    price: 400
  Sheep:
    active: true
    name: "&fSheep"
    price: 450
  Chicken:
    active: true
    name: "&6Chicken"
    price: 600
  Ocelot:
    active: true
    name: "&aOcelot"
    price: 700
  Slime:
    active: true
    name: "&3Slime"
    price: 650
  Wolf:
    active: true
    name: "&7Wolf"
    price: 500
  Mushroom_cow:
    active: true
    name: "&cMushroom Cow"
    price: 800
  Silverfish:
    active: true
    name: "&7Silverfish"
    price: 1000
  Rainbow_sheep:
    active: true
    name: "&5Ra&6in&3bow &cSh&beep"
    price: 2000

#
# POTIONS EFFECTS
# YOU CAN DELETE AND ADD LEVELS
# the cost MUST be a natural number greater than 0
PotionsEffects:
  # How many levels will be added to the pet level for each effects upgrade bought
  increasePetLevel: 5
  # you can find more info about effects here: https://minecraft.gamepedia.com/Status_effect#Haste
  speed:
    active: true
    levelsCosts:
      1: 300
      2: 600
      3: 1000
      4: 2000
  regeneration:
    active: true
    levelsCosts:
      1: 500
      2: 800
      3: 1200
      4: 2000
  fire_resistance:
    active: true
    levelsCosts:
      1: 200
      2: 500
      3: 600
      4: 1000
  night_vision:
    active: true
    levelsCosts:
      1: 1000
  increase_damage:
    active: true
    levelsCosts:
      1: 600
      2: 1000
      3: 2100
  invisibility:
    active: true
    levelsCosts:
      1: 2000
  water_breathing:
    active: true
    levelsCosts:
      1: 1500

### DO NOT TOUCH ###
ConfigVersion: 1.1
