######################
#                                              #
#       UpgradablesPets Plugin      #
#   developed by SpaicyGaming  #
#                                              #
#######################

Storage:
  # flatfile - mysql - mongodb
  type: flatfile

   # Database Credentials
  credentials:
    hostname: localhost
    database: UpgradablesPets

    # if "default" the plugin automatically uses the default port:
    # MySQL: 3306
    # MongoDB: 27017
    port: default

    # Affects only MongoDB connections (by default mongodb has no enabled access control)
    authentication: false

    username: root
    password: password

  #  MySQL Table prefix / MongoDB Collection prefix
  tablePrefix: 'UP_'

MainSettings:
  currency: "$"
  spawnPetAtJoin: true
  babyPets: true

  # If enabled the plugin will override all mob spawning restrictions (such as WorldGuard's mob-spawning flag)
  overrideSpawningRestrictions: true

  petName:
    # %owner% => Pet owner name
    # %name% => Pet name (default names are in the next section)
    # %petLvl% => Pet level
    # %maxHealth% => Pet max health  value
    # %maxHealthLvl% => Pet max health level
    # %totalCost% => Amount of money spent since the pet was bought
    format: "&b%owner%'s &6%name% &c(lvl.%petLvl%)"
    maxLength: 25
    # These words can't be used in pet's name (Bypass permission: upgradablespets.rename.bypassbl)
    blacklistedWords:
      - whateveryouwant

  showPetHereMsg: true
  showPetAwayMsg: true

  # Pet respawn delay in minutes
  petRespawnDelay: 1

  # Open gui on right click on pet
  openGuiOnRightClick: true

  # Open the gui on '/pet'
  openGuiOnSlashPet: false

  # Remove all potion effects on '/pet away'
  removeEffectsOnPetAway: true

  # True -> Send a message when a player try to hiurt his own pet.
  sendCantHitMessage: true

  # Players without the permission 'upgradablespets.world.*' can't use their pet in these worlds
  blacklistedWorlds:
    - world_without_pets

  # https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html
  petPurchaseDateFormat: "MM/dd/yy HH:mm"

  # How many levels will be added to the pet level for each upgrade (max health - potion effect)
  increasePetLevel: 5

  Sheep:
    # Prevent sheeps from eating grass
    preventGrassEating: true
    # All available colors (for 1.12.2): https://hub.spigotmc.org/javadocs/spigot/org/bukkit/DyeColor.html
    defaultColor: WHITE

# To buy a vip pet a player needs the permission "upgradablespets.vip.pet_to_lower_case". Example: "upgradablespets.vip.rainbow_sheep"
PetsCost:
  Cow:
    active: true
    forVips: false
    # If you change the name, "purchase pet" signs you created before won't work anymore
    name: "&bCow"
    price: 500
    # You can add/remove all the levels you want, except the level "1"
    maxHealth:
      # The default max health level
      1:
        value: 7.0
      2:
        value: 11.0
        cost: 2000
      3:
        value: 15.0
        cost: 5000
  Pig:
    active: true
    forVips: false
    name: "&dPig"
    price: 400
    maxHealth:
      1:
        value: 7.0
      2:
        value: 11.0
        cost: 2000
      3:
        value: 15.0
        cost: 5000
  Sheep:
    active: true
    forVips: false
    name: "&fSheep"
    price: 450
    maxHealth:
      1:
        value: 7.0
      2:
        value: 11.0
        cost: 2000
      3:
        value: 15.0
        cost: 5000
  Chicken:
    active: true
    forVips: false
    name: "&6Chicken"
    price: 600
    maxHealth:
      1:
        value: 7.0
      2:
        value: 11.0
        cost: 2000
      3:
        value: 15.0
        cost: 5000
  Ocelot:
    active: true
    forVips: false
    name: "&aOcelot"
    price: 700
    maxHealth:
      1:
        value: 10.0
      2:
        value: 15.0
        cost: 2000
      3:
        value: 20.0
        cost: 5000
  Slime:
    active: true
    forVips: false
    name: "&3Slime"
    price: 650
    maxHealth:
      1:
        value: 7.0
      2:
        value: 11.0
        cost: 2000
      3:
        value: 15.0
        cost: 5000
  Wolf:
    active: true
    forVips: false
    name: "&7Wolf"
    price: 500
    maxHealth:
      1:
        value: 7.0
      2:
        value: 11.0
        cost: 2000
      3:
        value: 15.0
        cost: 5000
  Mushroom_cow:
    active: true
    forVips: false
    name: "&cMushroom Cow"
    price: 800
    maxHealth:
      1:
        value: 8.0
      2:
        value: 13.0
        cost: 3000
      3:
        value: 17.0
        cost: 8000
  Silverfish:
    active: true
    forVips: false
    name: "&7Silverfish"
    price: 1000
    maxHealth:
      1:
        value: 5.0
      2:
        value: 11.0
        cost: 4500
      3:
        value: 15.0
        cost: 10000
  Rainbow_sheep:
    active: true
    forVips: false
    name: "&5Ra&6in&3bow &cSh&beep"
    price: 2000
    maxHealth:
      1:
        value: 12.0
      2:
        value: 15.0
        cost: 8000
      3:
        value: 20.0
        cost: 14000
#
# POTIONS EFFECTS
# YOU CAN DELETE AND ADD LEVELS
# the cost MUST be a natural number greater than 0
PotionsEffects:
  speed:
    active: true
    levelsCosts:
      1: 300
      2: 600
      3: 1000
      4: 2000
  regeneration:
    active: true
    levelsCosts:
      1: 500
      2: 800
      3: 1200
      4: 2000
  fire_resistance:
    active: true
    levelsCosts:
      1: 200
      2: 500
      3: 600
      4: 1000
  night_vision:
    active: true
    levelsCosts:
      1: 1000
  increase_damage:
    active: true
    levelsCosts:
      1: 600
      2: 1000
      3: 2100
  invisibility:
    active: true
    levelsCosts:
      1: 2000
  water_breathing:
    active: true
    levelsCosts:
      1: 1500

### DO NOT TOUCH ###
ConfigVersion: 2.3
